version: "3.9"

services:
  app:
    build: .
    container_name: hotel-booking-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/hotel-aggregator
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: hotel-booking-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
